import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";

import { ClerkProvider } from "@clerk/nextjs";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/app/(routes)/(root)/components/AppSidebar/AppSidebar";
import { Navbar, Footer } from "@/components/shared";
import { Toaster } from "@/components/ui/sonner";
import React from "react";

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className={spaceGrotesk.variable}>
        <body className="antialiased">
          {/* Toaster deve estar fora do provedor de contexto de UI */}
          <Toaster />

          <SidebarProvider>
            <div className="flex flex-col w-full min-h-screen bg-stone-100">
              <Navbar />

              <div className="flex flex-1">
                <AppSidebar />
                <main className="flex-1 p-4">{children}</main>
              </div>

              <Footer />
            </div>
          </SidebarProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
